#!/usr/bin/env python3
"""Passe YouTube « - Topic » (EPIC-033) — dernier rideau sur les clés none.

Ciblage RESTREINT par construction (plausibilité « musique récente ») :
  - clés 'none' de TOUS les caches (reform v1/v2, année, discogs, itunes…) ;
  - artiste ET titre présents (junk-artiste exclus — déjà couvert par reform2) ;
  - PLAUSIBLES ≥ 2015 : au moins un fichier de la clé dans un dossier dont le
    chemin porte une année 2015-2026 ('select_2021_10_23', '2024_02_14'…).
    Les clés sans aucun signal d'année ne sont PAS ciblées : sur du vieux
    catalogue, la release_date Topic vaut souvent réédition, pas 1ʳᵉ sortie.

Requête = reformulation reform2 (junk de tête retiré) envoyée à yt-dlp
(ytsearch8, mode flat : 1 seule requête réseau par clé).

GARDE-FOUS d'acceptation (mashup/slowed/remix sont fréquents sur YT) :
  1. chaîne se terminant par « - Topic » (obligatoire) ;
  2. TOUS les tokens de l'artiste ET du titre (hors tokens junk : chiffres
     purs type '01') présents dans le titre de la vidéo ;
  3. durée ± 15 s d'au moins un fichier de la clé ;
  4. release_date présent (extraction complète de la vidéo — un flat ne
     l'expose pas) ; l'upload_date n'est JAMAIS utilisé (compilations).

Classification : 0 concluant → none ; 1 → lax (revue) ; ≥2 même année →
found si cohérent (release_year ≥ plausible−2, sinon ambiguous) ; ≥2 années
distinctes → ambiguous. found = consensus de plusieurs vidéos officielles
indépendantes ; lax reste en revue humaine (jamais appliqué automatiquement).

TIER --verified (chaînes officielles vérifiées / art tracks fusionnés) :
YouTube fusionne depuis 2025-2026 les chaînes « - Topic » dans les profils
artiste (release_date souvent perdue). Le tier 2 élargit aux chaînes
channel_is_verified (extraction complète — pas visible en flat) avec les
MÊMES garde-fous tokens + durée ± 15 s, et l'année prise sur :
  - release_date si encore présente, OU
  - la description d'art track auto-généré (signature « Auto-generated by
    YouTube. ») : ligne « Released on: AAAA-MM-JJ » ou « ℗ AAAA … ».
Les descriptions promo (« Buy / Stream: … ») ne donnent JAMAIS d'année.
TOUT est classé lax : aucun found en tier vérifié — la revue humaine tranche
(la vue Années affiche les candidates, apply_years n'applique que le found
du tier topic ; youtube_topic_strict ne prend que status='found').
Une clé déjà conclusive (lax/ambiguous/found) n'est jamais re-requêtée ; une
clé 'none' du mode topic est RE-INTERROGÉE en mode --verified (et inversement),
chaque enregistrement journalisé porte son mode.

Journal : data/youtube_topic_cache.jsonl {key, artist, title, n_files, query,
status, source, year, years, videos}. Reprise : clés présentes sautées, lignes
'error' re-jetables.

APERÇU PAR DÉFAUT : sans --go, le script n'interroge RIEN — décomptes de
ciblage + échantillon de requêtes. --go lance le run réel (~5 s/clé).

Usage : ./venv/bin/python scripts/collect_youtube_topic.py [--go]
        [--verified] [--limit=N] [--report] — depuis la racine du projet.
"""
import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import time
from collections import Counter

sys.path.insert(0, 'scripts')
import collect_discogs_reform2 as r2
from collect_years import artist_title, load_keys, tokens

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE = os.path.join(ROOT, 'data', 'cache.json')
PROG = os.path.join(ROOT, 'data', 'youtube_topic_cache.jsonl')
NONE_CACHES = [os.path.join(ROOT, 'data', 'discogs_reform_cache.jsonl'),
               os.path.join(ROOT, 'data', 'discogs_reform2_cache.jsonl')]

YT_DLP = shutil.which('yt-dlp') or os.path.expanduser('~/.local/bin/yt-dlp')
YEAR_EV = re.compile(r'(?<!\d)(19|20)\d{2}(?!\d)')
TOPIC_SUFFIX = ' - topic'
AUTOGEN = 'auto-generated by youtube'   # signature d'art track (description)
REL_LINE = re.compile(r'released on:\s*((?:19|20)\d{2})')
P_LINE = re.compile(r'\u2117\s*((?:19|20)\d{2})')   # ℗ AAAA
DUR_TOL = 15          # ±15 s (cf. tolerant_discogs_match du projet)
SEARCH_N = 15         # résultats examinés par requête (1 seule page réseau)
SLEEP = 2.0           # politesse entre clés (pages publiques, pas d'API)


# ── Ciblage ────────────────────────────────────────────────────────────────

def last_status_none(path):
    """Clés au dernier statut 'none' d'un cache jsonl (lignes error ignorées)."""
    last = {}
    try:
        with open(path) as f:
            for line in f:
                line = line.strip()
                if line:
                    r = json.loads(line)
                    if r.get('status') == 'error':
                        continue
                    last[r['key']] = r['status']
    except FileNotFoundError:
        pass
    return {k for k, st in last.items() if st == 'none'}


def dirs_of_key(cache, key):
    """Dossiers (dirname) de tous les fichiers d'une clé dans cache.json."""
    dirs = set()
    for side in ('source', 'epars'):
        for base, files in cache.get(side, {}).items():
            for fn, meta in files.items():
                ka, kt = artist_title(fn)
                if (ka or '') + '\t' + (kt or '') == key:
                    dirs.add(os.path.dirname(os.path.join(
                        base, meta.get('path', fn))))
    return dirs


def plausible_year(dirs):
    """Année-max plausibilité d'une clé : année 20xx portée par un chemin de
    dossier ; None si aucun signal."""
    ys = [int(m.group(0)) for d in dirs for m in YEAR_EV.finditer(d)]
    return max(ys) if ys else None


def targets(cache=None, none_caches=None):
    """Clés cibles : none partout, artiste+titre, plausible ≥ 2015.
    Retourne [(key, n, durs, plausible)]."""
    cache = cache if cache is not None else json.load(open(CACHE))
    none_caches = none_caches if none_caches is not None else NONE_CACHES
    none_keys = set()
    for p in none_caches:
        none_keys |= last_status_none(p)
    return _build_targets(cache, none_keys)


def _build_targets(cache, none_keys):
    """Cœur pur du ciblage (testable sans réseau ni fichiers réels)."""
    _, _, keys = _load_keys_safe()
    out = []
    for k in sorted(none_keys):
        info = (keys or {}).get(k)
        a, t = k.split('\t', 1)
        if not a or not t:
            continue                     # junk-artiste : hors périmètre
        durs = info['durs'] if info else set()
        n = info['n'] if info else 0
        if not n:
            continue
        py = plausible_year(dirs_of_key(cache, k))
        if py is None or py < 2015:
            continue                     # pas plausible ≥ 2015
        out.append((k, n, durs, py))
    return out


def _load_keys_safe():
    try:
        return load_keys()
    except FileNotFoundError:
        return 0, 0, {}


# ── Recherche / matching ───────────────────────────────────────────────────

def yt_search(query, n=SEARCH_N):
    """Recherche yt-dlp flat : [{id, title, channel, duration}, …]."""
    out = subprocess.run(
        [YT_DLP, '--no-warnings', '--flat-playlist', '--dump-json',
         f'ytsearch{n}:{query}'],
        capture_output=True, text=True, timeout=120)
    entries = []
    for line in out.stdout.splitlines():
        line = line.strip()
        if line:
            e = json.loads(line)
            entries.append({'id': e.get('id'), 'title': e.get('title') or '',
                            'channel': e.get('channel') or '',
                            'duration': e.get('duration')})
    return entries


def _full(video_id):
    """Extraction complète d'une vidéo (release_date requis)."""
    out = subprocess.run(
        [YT_DLP, '--no-warnings', '--dump-json', '--skip-download',
         f'https://www.youtube.com/watch?v={video_id}'],
        capture_output=True, text=True, timeout=120)
    if out.returncode != 0:
        return None
    return json.loads(out.stdout)


def match_tokens(artist, title):
    """Tokens exigés dans le titre vidéo : artiste complet + titre hors junk
    (chiffres purs '01'… — cf. junk_word de reform2)."""
    tt = {w for w in tokens(title) if not r2.junk_word(w)}
    return tt | tokens(artist)


def classify(hits, plausible, found_allowed=True):
    """[(id, title, year)] → (status, year, years). Règles du docstring.
    found_allowed=False (tier --verified) : TOUT en lax, jamais de found."""
    if not hits:
        return 'none', None, []
    years = sorted({h['year'] for h in hits})
    if len(years) == 1:
        if len(hits) == 1 or not found_allowed:
            return 'lax', years[0], years   # revue humaine
        coherent = plausible is None or int(years[0]) >= plausible - 2
        return ('found' if coherent else 'ambiguous'), years[0], years
    return 'ambiguous', None, years


def lookup(key, n_files, durs, plausible, verified=False):
    """Une clé → enregistrement journal (recherche + extraction + classement).
    verified=False : chaînes « - Topic », release_date requis, lax/found.
    verified=True : chaînes vérifiées (fusionnées), année release_date ou
    description d'art track, TOUT en lax."""
    artist, title = key.split('\t', 1)
    ra, rt = r2.reform2(artist, title)
    q = r2._norm(f'{ra} {rt}')
    rec = {'key': key, 'artist': artist, 'title': title, 'n_files': n_files,
           'query': q, 'status': 'none', 'source': 'youtube', 'year': None,
           'years': [], 'videos': [], 'plausible': plausible,
           'mode': 'verified' if verified else 'topic'}
    if not tokens(rt):
        return rec
    entries = yt_search(q)
    if verified:
        # extraction complète uniquement des candidats pré-filtrés tokens+durée
        need = match_tokens(ra, rt)
        cands = [e for e in entries
                 if need <= tokens(e['title'])
                 and (not durs or not e.get('duration')
                      or any(abs(e['duration'] - d) <= DUR_TOL for d in durs))]
        full_by_id = {}
        for c in cands[:6]:                  # garde-fou coût : ≤ 6 extractions
            full_by_id[c['id']] = _full(c['id'])
            time.sleep(0.5)
        final = match_verified(full_by_id, ra, rt, durs)
    else:
        hits = match_topic(entries, ra, rt, durs)
        final = []
        for h in hits:
            full = _full(h['id'])
            rd = (full or {}).get('release_date')
            if rd and len(str(rd)) >= 4 and str(rd)[:4].isdigit():
                final.append({'id': h['id'], 'title': h['title'],
                              'channel': h['channel'],
                              'year': str(rd)[:4]})
    rec['videos'] = final
    rec['status'], rec['year'], rec['years'] = classify(final, plausible,
                                                        not verified)
    return rec


def match_topic(entries, artist, title, durs):
    """Vidéos ' - Topic' passant tokens + durée. Retourne [(id, title, dur)]."""
    need = match_tokens(artist, title)
    hits = []
    for e in entries:
        if not e['channel'].strip().lower().endswith(TOPIC_SUFFIX):
            continue
        tt = tokens(e['title'])
        if not need <= tt:
            continue
        if durs and e.get('duration') and \
                not any(abs(e['duration'] - d) <= DUR_TOL for d in durs):
            continue
        hits.append(e)
    return hits


def year_from_desc(description):
    """Année d'une description d'art track auto-généré (artiste fusionné) :
    'Released on: AAAA…' ou '℗ AAAA …'. Les descriptions promo (« Buy /
    Stream: … ») n'ont ni l'une ni l'autre → None (jamais d'upload_date)."""
    d = (description or '').lower()
    if AUTOGEN not in d:
        return None
    m = REL_LINE.search(d) or P_LINE.search(d)
    return m.group(1) if m else None


def match_verified(full_by_id, artist, title, durs):
    """Tier vérifié : vidéos de chaîne channel_is_verified (extraction
    complète), MÊMES garde-fous tokens + durée, année = release_date OU
    description d'art track auto-généré. Retourne [(id, title, year, chan)]."""
    need = match_tokens(artist, title)
    hits = []
    for vid, full in full_by_id.items():
        if not full or not full.get('channel_is_verified'):
            continue
        tt = tokens(full.get('title') or '')
        if not need <= tt:
            continue
        dur = full.get('duration')
        if durs and dur and \
                not any(abs(dur - d) <= DUR_TOL for d in durs):
            continue
        year = (full.get('release_date') or '')[:4]
        if not year.isdigit():
            year = year_from_desc(full.get('description')) or ''
        if not year:
            continue
        hits.append({'id': vid, 'title': full.get('title') or '',
                     'channel': full.get('channel') or '', 'year': year})
    return hits


# ── Journal / run / rapport ────────────────────────────────────────────────

def done_keys(path=PROG):
    done = {}
    try:
        with open(path) as f:
            for line in f:
                line = line.strip()
                if line:
                    r = json.loads(line)
                    if r.get('status') == 'error':
                        continue
                    done[r['key']] = r
    except FileNotFoundError:
        pass
    return done


def _append(rec, path=PROG):
    with open(path, 'a') as f:
        f.write(json.dumps(rec, ensure_ascii=False) + '\n')


def preview(limit=25):
    todo = targets()
    py = Counter(k[3] for k in todo)
    print(f'clés cibles (none, artiste+titre, plausible ≥ 2015) : {len(todo)}')
    print('par année plausible :', dict(sorted(py.items())))
    print(f'\n— requêtes ({min(limit, len(todo))} affichées) —')
    for k, n, durs, p in todo[:limit]:
        a, t = k.split('\t', 1)
        ra, rt = r2.reform2(a, t)
        print(f'  [{r2._norm(f"{ra} {rt}")[:52]:<52}] plausible={p} n={n}')


def run(limit=None, verified=False):
    mode = 'verified' if verified else 'topic'
    done = done_keys(PROG)
    # ré-interrogation : clé jamais vue, OU clé 'none' vue dans l'AUTRE mode
    # (une clé conclusive — lax/ambiguous/found — n'est jamais re-requêtée).
    # mode absent (enregistrements antérieurs à --verified) = 'topic'.
    todo = [(k, n, durs, p) for k, n, durs, p in targets()
            if (rec := done.get(k)) is None
            or (rec.get('status') == 'none'
                and (rec.get('mode') or 'topic') != mode)]
    if limit:
        todo = todo[:limit]
    print(f'clés youtube [{mode}] à interroger : {len(todo)} '
          f'(déjà faites : {len(done)})', flush=True)
    for i, (key, n, durs, p) in enumerate(todo):
        try:
            rec = lookup(key, n, durs, p, verified=verified)
        except Exception as e:
            artist, title = key.split('\t', 1)
            rec = {'key': key, 'artist': artist, 'title': title,
                   'n_files': n, 'query': '', 'status': 'error',
                   'source': 'youtube', 'year': None, 'years': [],
                   'videos': [], 'plausible': p, 'mode': mode,
                   'error': f'{type(e).__name__}: {e}'[:120]}
        _append(rec, PROG)
        print(f'[{i + 1}/{len(todo)}] {rec["query"][:36]} → {rec["status"]} '
              f'{rec["years"] or ""}', flush=True)
        time.sleep(SLEEP)


def report():
    done = done_keys()
    st = Counter((r.get('mode') or 'topic', r['status'])
                 for r in done.values())
    print(f'=== RAPPORT YOUTUBE ({len(done)} clés valides) ===')
    for (mode, status), n in sorted(st.items()):
        print(f'  [{mode:<8}] {status:<10} {n}')
    for kind in ('found', 'lax', 'ambiguous'):
        rows = [r for r in done.values() if r['status'] == kind][:8]
        if rows:
            print(f'— {kind} —')
            for r in rows:
                v = (r.get('videos') or [{}])[0]
                print(f'  [{r["query"][:36]}] → {r.get("year") or r.get("years")} '
                      f'({v.get("channel", "?")} · {v.get("id", "")})')


if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('--go', action='store_true',
                    help='lancer réellement (défaut : aperçu lecture-seule)')
    ap.add_argument('--verified', action='store_true',
                    help='tier 2 : chaînes officielles vérifiées (fusionnées), '
                         'année release_date ou description art track, TOUT en lax')
    ap.add_argument('--limit', type=int, default=None)
    ap.add_argument('--report', action='store_true')
    args = ap.parse_args()
    if args.report:
        report()
    elif args.go:
        run(args.limit, verified=args.verified)
    else:
        preview()
